ARCH_FLAGS=-D__CORTEX_M4 -D__USE_CMSIS

GCC_ARCH_FLAGS:=-mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16

FLOAT_ABI=-mfloat-abi=softfp
CFLAGS_ARCH:=$(GCC_ARCH_FLAGS) $(FLOAT_ABI)
CXXFLAGS_ARCH:=$(GCC_ARCH_FLAGS) $(FLOAT_ABI)
AFLAGS_ARCH:=$(GCC_ARCH_FLAGS) $(FLOAT_ABI)
LFLAGS_ARCH:=$(GCC_ARCH_FLAGS) $(FLOAT_ABI)

